#!/usr/bin/env bash

# Détection du système

function checkSystem
{
    # Le fichier /etc/os-release est présent sur les OS récents et permet de récupérer toutes les infos nécéssaires
    if [ -f "/etc/os-release" ];then
        if grep -q "^ID_LIKE=" /etc/os-release;then
            OS_FAMILY=$(grep "^ID_LIKE=" /etc/os-release | cut -d'=' -f2 | sed 's/"//g')
        fi
        if grep -q "^ID=" /etc/os-release;then
            OS_FAMILY=$(grep "^ID=" /etc/os-release | cut -d'=' -f2 | sed 's/"//g')
        fi
        
        if [ -z "$OS_FAMILY" ];then
            echo -e "[${RED} ERROR ${RESET}] Unknown OS family"
            exit
        fi

        # Si OS_FAMILY contient l'un des termes suivants alors c'est la famille redhat
        if echo "$OS_FAMILY" | egrep -q -i 'rhel|centos|fedora';then
            OS_FAMILY="Redhat"
        fi

        # Si OS_FAMILY contient l'un des termes suivants alors c'est la famille debian
        if echo "$OS_FAMILY" | egrep -q -i 'debian|ubuntu|kubuntu|xubuntu|armbian|mint';then
            OS_FAMILY="Debian"
        fi

        # Enfin si OS_FAMILY n'est ni égale à Redhat ni à Debian alors on est sur un OS non pris en charge
        if ! echo "$OS_FAMILY" | egrep -q -i 'Redhat|Debian';then
            echo -e "[${RED} ERROR ${RESET}] Unsupported OS family ($OS_FAMILY)"
            exit
        fi

        # Toujours à partir de /etc/os-release, on récupère le nom de l'OS et sa version
        OS_NAME=$(grep "^ID=" /etc/os-release | cut -d'=' -f2 | sed 's/"//g')
        if [ -z "$OS_NAME" ];then
            echo -e "[${RED} ERROR ${RESET}] Unknown OS name"
            exit
        fi

        OS_VERSION=$(grep "^VERSION_ID=" /etc/os-release | cut -d'=' -f2 | sed 's/"//g')
        if [ -z "$OS_VERSION" ];then
            echo -e "[${RED} ERROR ${RESET}] Unknown OS release"
            exit
        fi
    fi

    # Cas où /etc/os-release n'existe pas
    if [ ! -f "/etc/os-release" ];then
        # Si apt est présent, on est sur un os de la famille Debian
        if [ -f "/usr/bin/apt" ];then
            OS_FAMILY="Debian"
        fi
        # Si yum ou dnf est présent, on est sur un os de la famille Redhat
        if [ -f "/usr/bin/yum" ] || [ -f "/usr/bin/dnf" ];then
            OS_FAMILY="Redhat"
        fi

        # A ce stade si OS_FAMILY est vide alors on est sur un OS non pris en charge
        if [ -z "$OS_FAMILY" ];then
            echo -e "[${RED} ERROR ${RESET}] Unknown OS family, unsupported system"
            exit
        fi

        # /usr/bin/lsb_release est un programme uniquement présent sur les OS de la famille Debian
        if [ -f "/usr/bin/lsb_release" ];then
            OS_NAME=$(lsb_release -a 2> /dev/null | grep 'Distributor ID:' | awk '{print $NF}')
            OS_VERSION=$(lsb_release -a 2> /dev/null | grep 'Release:' | awk '{print $NF}')
        fi

        # Dernier recours pour les OS de la famille Redhat
        # Si /etc/centos-release existe, c'est un centos
        if [ -f "/etc/centos-release" ];then
            OS_NAME="CentOS"
            OS_ID="centos"
            OS_VERSION=$(rpm --eval '%{centos_ver}')
        # Si /etc/fedora-release existe, c'est un fedora
        elif [ -f "/etc/fedora-release" ];then
            OS_NAME="Fedora"
            OS_ID="fedora"
            OS_VERSION=$(cat /etc/os-release | grep "^VERSION_ID" | cut -d'=' -f2 | sed 's/"//g')
        else
            # Dernier recours on vérifie la présence d'un fichier os-release sinon on quitte
            if [ ! -f "/etc/os-release" ];then
                echo -e "[${RED} ERROR ${RESET}] Cannot determine OS release"
                exit
            fi

            OS_NAME=$(cat /etc/os-release | grep "^NAME=" | cut -d'=' -f2 | sed 's/"//g')
            OS_ID=$(cat /etc/os-release | grep "^ID=" | cut -d'=' -f2 | sed 's/"//g')
            OS_VERSION=$(cat /etc/os-release | grep "^VERSION_ID=" | cut -d'=' -f2 | sed 's/"//g')
        fi

        # On quitte le script si on n'a rien trouvé à ce stade
        if [ -z "$OS_NAME" ];then
            echo -e "[${RED} ERROR ${RESET}] Unknown OS name"
            exit
        fi 
        if [ -z "$OS_VERSION" ];then
            echo -e "[${RED} ERROR ${RESET}] Unknown OS release"
            exit
        fi
    fi

    if [ "$OS_FAMILY" == "Debian" ];then
        PKG_MANAGER="/usr/bin/apt"
        PKG_TYPE="deb"
    fi
    if [ "$OS_FAMILY" == "Redhat" ];then
        if [ -f "/usr/bin/yum" ];then
            PKG_MANAGER="/usr/bin/yum"
        fi
        if [ -f "/usr/bin/dnf" ];then
            PKG_MANAGER="/usr/bin/dnf"
        fi
        # Si les deux sont présents (fedora) alors on utilisera yum de préférence
        if [ -f "/usr/bin/yum" ] && [ -f "/usr/bin/dnf" ];then
            PKG_MANAGER="/usr/bin/yum"
        fi

        PKG_TYPE="rpm"
    fi
}