#!/usr/bin/env bash
# Cette fonction vérifie si les dépendances du script sont bien installées.

function checkDependencies
{
    CHECK_DEP=""
    CHECK_LOCALE=""

    echo -e " Checking dependencies...\n"

    # Dépendances Debian :
    if [ "$OS_FAMILY" == "Debian" ];then
        # apt-transport-https
        CHECK_DEP=$(dpkg -l | grep " apt-transport-https " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            apt-get -o Acquire::Check-Valid-Until=false -qq --allow-releaseinfo-change update &&
            echo -ne " Installing apt-transport-https\t" &&
            apt-get -qq install apt-transport-https -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
        # aptitude
        CHECK_DEP=$(dpkg -l | grep " aptitude " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            apt-get -o Acquire::Check-Valid-Until=false -qq --allow-releaseinfo-change update &&
            echo -ne " Installing aptitude\t" &&
            apt-get -qq install aptitude -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
        # mutt
        CHECK_DEP=$(dpkg -l | grep " mutt " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            apt-get -o Acquire::Check-Valid-Until=false -qq --allow-releaseinfo-change update &&
            echo -ne " Installing mutt\t" &&
            apt-get -qq install mutt -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
        # locales
        CHECK_DEP=$(dpkg -l | grep " locales " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing locales\t" &&
            apt-get -qq install locales -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
        # ngrep
        CHECK_DEP=$(dpkg -l | grep " ngrep " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing ngrep\t" &&
            apt-get -qq install ngrep -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
        # jq
        CHECK_DEP=$(dpkg -l | grep " jq " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing jq\t" &&
            apt-get -qq install jq -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
        # inotify
        CHECK_DEP=$(dpkg -l | grep " inotify-tools " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing inotify-tools\t" &&
            apt-get -qq install inotify-tools -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
        # virt-what
        CHECK_DEP=$(dpkg -l | grep " virt-what " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            apt-get -o Acquire::Check-Valid-Until=false -qq --allow-releaseinfo-change update &&
            echo -ne " Installing virt-what\t" &&
            apt-get -qq install virt-what -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
        # configuration des locales
        # CHECK_LOCALE=$(/usr/bin/locale | grep "LANG=fr_FR.UTF-8")
        # if [ -z "$CHECK_LOCALE" ];then
        #     echo -ne "Configuration des locales en Français " &&
        #     locale-gen --purge fr_FR.UTF-8 > /dev/null &&
        #     echo -e 'LANG="fr_FR.UTF-8"' > /etc/default/locale &&
        #     echo -e "[$GREEN OK $RESET]"
        # fi
    fi

    # Dépendances Redhat :
    if [ "$OS_FAMILY" == "Redhat" ];then
        # mutt
        CHECK_DEP=$(rpm -qa mutt)
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing mutt\t" &&
            yum install mutt -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
        # yum-utils
        CHECK_DEP=$(rpm -qa yum-utils)
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing yum-utils\t" &&
            yum install yum-utils -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
        # jq
        CHECK_DEP=$(rpm -qa jq)
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing jq\t" &&
            yum install jq -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
        # inotify
        CHECK_DEP=$(rpm -qa inotify-tools)
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing inotify-tools\t" &&
            yum install inotify-tools -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
        # ngrep
        CHECK_DEP=$(rpm -qa ngrep)
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing ngrep\t" &&
            yum install ngrep -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
        # virt-what
        CHECK_DEP=$(rpm -qa virt-what)
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing virt-what\t" &&
            yum install virt-what -y > /dev/null &&
            echo -e "[$GREEN OK $RESET]"
        fi
    fi
}