#!/usr/bin/env bash
# Cette fonction vérifie si les dépendances du script sont bien installées.

function checkDependencies
{
    CHECK_DEP=""
    CHECK_LOCALE=""

    echo -e " Checking dependencies...\n"

    # Dépendances Debian :
    if [ "$OS_FAMILY" == "Debian" ];then
        # apt-transport-https
        CHECK_DEP=$(dpkg -l | grep " apt-transport-https " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            apt-get -o Acquire::Check-Valid-Until=false -qq --allow-releaseinfo-change update &&
            echo -ne " Installing apt-transport-https..." &&
            apt-get -qq install apt-transport-https -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # aptitude
        CHECK_DEP=$(dpkg -l | grep " aptitude " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            apt-get -o Acquire::Check-Valid-Until=false -qq --allow-releaseinfo-change update &&
            echo -ne " Installing aptitude..." &&
            apt-get -qq install aptitude -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # mutt
        CHECK_DEP=$(dpkg -l | grep " mutt " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            apt-get -o Acquire::Check-Valid-Until=false -qq --allow-releaseinfo-change update &&
            echo -ne " Installing mutt..." &&
            apt-get -qq install mutt -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # locales
        CHECK_DEP=$(dpkg -l | grep " locales " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing locales..." &&
            apt-get -qq install locales -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # ngrep
        CHECK_DEP=$(dpkg -l | grep " ngrep " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing ngrep..." &&
            apt-get -qq install ngrep -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # jq
        CHECK_DEP=$(dpkg -l | grep " jq " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing jq..." &&
            apt-get -qq install jq -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # inotify
        CHECK_DEP=$(dpkg -l | grep " inotify-tools " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing inotify-tools..." &&
            apt-get -qq install inotify-tools -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # virt-what
        CHECK_DEP=$(dpkg -l | grep " virt-what " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            apt-get -o Acquire::Check-Valid-Until=false -qq --allow-releaseinfo-change update &&
            echo -ne " Installing virt-what..." &&
            apt-get -qq install virt-what -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # net-tools
        CHECK_DEP=$(dpkg -l | grep " net-tools " | grep "ii")
        if [ -z "$CHECK_DEP" ];then
            apt-get -o Acquire::Check-Valid-Until=false -qq --allow-releaseinfo-change update &&
            echo -ne " Installing net-tools..." &&
            apt-get -qq install net-tools -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
    fi

    # Dépendances Redhat :
    if [ "$OS_FAMILY" == "Redhat" ];then
        # mutt
        CHECK_DEP=$(rpm -qa mutt)
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing mutt..." &&
            yum install mutt -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # yum-utils
        CHECK_DEP=$(rpm -qa yum-utils)
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing yum-utils..." &&
            yum install yum-utils -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # jq
        CHECK_DEP=$(rpm -qa jq)
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing jq..." &&
            yum install jq -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # inotify
        CHECK_DEP=$(rpm -qa inotify-tools)
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing inotify-tools..." &&
            yum install inotify-tools -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # ngrep
        CHECK_DEP=$(rpm -qa ngrep)
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing ngrep..." &&
            yum install ngrep -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # virt-what
        CHECK_DEP=$(rpm -qa virt-what)
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing virt-what..." &&
            yum install virt-what -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
        # net-tools
        CHECK_DEP=$(rpm -qa net-tools)
        if [ -z "$CHECK_DEP" ];then
            echo -ne " Installing net-tools..." &&
            yum install net-tools -y > /dev/null &&
            echo -e "$GREEN OK $RESET"
        fi
    fi
}