#!/usr/bin/env bash
# Si il s'agit de la première configuration du script

function configure
{
    echo -e "This software is intended to interactively or automatically update your Linux system."
    echo -e "Additional modules can be enabled to bring additional features."

    echo -ne "\n${YELLOW} Start installation now? (yes/no) : $RESET"; read -p "" CONFIRM &&
    if [ "$CONFIRM" != "yes" ];then
        clean_exit
    fi

    # Vérifications avant de commencer
    if [ -z "$OS_FAMILY" ];then
        echo -e "[$YELLOW ERROR $RESET] Unknown OS"
        clean_exit
    fi
    if [ -z "$PKG_MANAGER" ];then
        echo -e "[$YELLOW ERROR $RESET] Unknown package manager"
        clean_exit
    fi

    # Configuration générale
    echo -e "\n ${YELLOW}Main configuration\n${RESET}"

    echo -ne " Specify a host's configuration profile (e.g: app, db, PC,...) or leave empty: ";read -p "" PROFILE
    if [ -z "$PROFILE" ];then
        PROFILE="Host"
    fi

    echo -ne " Specify host environment (default: prod) : ";read -p "" SERVER_ENV
    # Si laissé vide, on met une valeur par défaut (prod)
    if [ -z "$SERVER_ENV" ];then
        SERVER_ENV="prod"
    fi

    echo -ne " Receive update reports by mail (yes/no) : ";read -p "" CONFIRM
    if [ "$CONFIRM" == "yes" ];then 
        MAIL_ENABLED="yes"
        echo -ne " Specify mail recipient(s) where to end those reports (separated by a comma): ";read -p "" MAIL_RECIPIENT
    else
        MAIL_ENABLED="no"
    fi

    echo -ne " Automatically check and install new available release of this program (yes/no) : ";read -p "" ALLOW_SELF_UPDATE

    # Configuration des exclusions
    echo -ne " Specify what package to exclude on major version update (separated by a comma) (leave empty if none) : ";read -p "" CONF_SOFT_EXCLUDE_MAJOR
    echo -ne " Specify what package to exclude no matter the version (separated by a comma) (leave empty if none) : ";read -p "" CONF_SOFT_EXCLUDE
    echo -ne " Specify what service to restart after package update (leave empty if none) : ";read -p "" CONF_SOFT_NEED_RESTART

    # Génération du fichier de configuration
    echo -ne "\nGenerating configuration file: "
    echo -e "# Configuration file for linupdate on $HOSTNAME" > $CONF
    echo "[CONFIGURATION]" >> $CONF
    echo "PROFILE=\"$PROFILE\"" >> $CONF
    echo "ENV=\"$SERVER_ENV\"" >> $CONF
    echo "MAIL_ENABLED=\"$MAIL_ENABLED\"" >> $CONF
    echo "MAIL_RECIPIENT=\"$MAIL_RECIPIENT\"" >> $CONF
    echo "ALLOW_SELF_UPDATE=\"$ALLOW_SELF_UPDATE\"" >> $CONF
    echo -e "\n[SOFTWARE CONFIGURATION]" >> $CONF
    echo "EXCLUDE_MAJOR=\"$CONF_SOFT_EXCLUDE_MAJOR\"" >> $CONF
    echo "EXCLUDE=\"$CONF_SOFT_EXCLUDE\"" >> $CONF
    echo "NEED_RESTART=\"$CONF_SOFT_NEED_RESTART\"" >> $CONF
    # echo "KEEP_CRON=\"no\"" >> $CONF
    echo -e "[$GREEN OK $RESET]\n"

    echo -ne "Execute linupdate now? (yes/no) : ";read -p "" CONFIRM
    if [ "$CONFIRM" != "yes" ];then
        clean_exit
    fi
}