#!/bin/bash

function disableSelfUpdate
{
    if [ ! -f "$CONF" ];then
        return
    fi

    sed -i 's/ALLOW_SELF_UPDATE.*/ALLOW_SELF_UPDATE="no"/g' "$CONF" &&

    echo -e "Mise à jour automatique de linupdate ${YELLOW}désactivée${RESET}"
}