#!/bin/bash

function enableSelfUpdate
{
    if [ ! -f "$CONF" ];then
        return
    fi

    sed -i 's/ALLOW_SELF_UPDATE.*/ALLOW_SELF_UPDATE="yes"/g' "$CONF" &&

    echo -e "Mise à jour automatique de linupdate ${YELLOW}activée${RESET}"
}