#!/usr/bin/env bash

function enableSelfUpdate
{
    if [ ! -f "$CONF" ];then
        return
    fi

    sed -i 's/ALLOW_SELF_UPDATE.*/ALLOW_SELF_UPDATE="yes"/g' "$CONF" &&

    echo -e "Linupdate automatic update ${YELLOW}enabled${RESET}"
}