#!/usr/bin/env bash
# Récupérer les modules à jour depuis github

function getModules
{
    TMP_DIR="/tmp/linupdate"
    rm "$TMP_DIR" -rf

    # Clonage du repo
    cd /tmp &&
    git clone --quiet https://github.com/lbr38/linupdate.git > /dev/null &&

    # Copie de tous les modules dans le répertoire de modules
    \cp -r ${TMP_DIR}/mods-available/* ${MODULES_DIR}/ &&
    rm "$TMP_DIR" -rf
}