#!/usr/bin/env bash

# Generate config file if not exist

function generateConf
{
    if [ -f "$CONF" ]; then
        return
    fi

    echo '[CONFIGURATION]' > "$CONF"
    echo 'PROFILE="Bare-metal"' >> "$CONF"
    echo 'ENV="prod"' >> "$CONF"
    echo 'MAIL_ENABLED="no"' >> "$CONF"
    echo 'MAIL_RECIPIENT=""' >> "$CONF"

    echo -e '\n[SOFTWARE CONFIGURATION]' >> "$CONF"
    echo 'EXCLUDE_MAJOR=""' >> "$CONF"
    echo 'EXCLUDE=""' >> "$CONF"
    echo 'NEED_RESTART=""' >> "$CONF"
}