#!/usr/bin/env bash
# Retrieve configuration from linupdate.conf

function getConf
{
    # If config file doesn't exist, exit
    if [ ! -f "$CONF" ];then
        echo -e "[${YELLOW} ERROR ${RESET}] No config file was found on this server. Use --install param to finalize linupdate installation.\n"
        (( UPDATE_ERROR++ ))

        # Delete log file 
        rm "$LOG" -f
        clean_exit
    fi

    PROFILE=$(egrep "^PROFILE=" "$CONF" | cut -d'=' -f 2 | sed 's/"//g')                        # Profile name
    ENV=$(egrep "^ENV=" "$CONF" | cut -d'=' -f 2 | sed 's/"//g')                                # Environment
    MAIL_ENABLED=$(egrep "^MAIL_ENABLED=" "$CONF" | cut -d'=' -f 2 | sed 's/"//g')              # Enable mail notification
    MAIL_RECIPIENT=$(egrep "^MAIL_RECIPIENT=" "$CONF" | cut -d'=' -f 2 | sed 's/"//g')          # Mail recipient
    PACKAGES_EXCLUDE_MAJOR=$(egrep "^EXCLUDE_MAJOR=" "$CONF" | cut -d'=' -f 2 | sed 's/"//g')   # Packages to exclude on a major update
    PACKAGES_EXCLUDE=$(egrep "^EXCLUDE=" "$CONF" | cut -d'=' -f 2 | sed 's/"//g')               # Packages to always exclude
    SERVICE_RESTART=$(egrep "^SERVICE_RESTART=" "$CONF" | cut -d'=' -f 2 | sed 's/"//g')        # Services to restart after update

    if [ -z "$PROFILE" ];then
        echo -e "[${RED} ERROR ${RESET}] No profile is defined\n"
        (( UPDATE_ERROR++ ))
        clean_exit
    fi

    if [ -z "$ENV" ];then
        echo -e "[${RED} ERROR ${RESET}] No environment is defined\n"
        (( UPDATE_ERROR++ ))
        clean_exit
    fi
}