#!/bin/bash

echo -e "Configuration automatique de linupdate et des fichiers .repo"
while [ -z "$PROFILE" ];do
	read -p " → Type de serveur, laissez vide pour afficher tous les types disponibles : " PROFILE
	if [ -z "$PROFILE" ];then # Si laissé vide, on affiche tous les types disponibles, pour cela on télécharge tous les types depuis le serveur de repo
		echo -e "$YELLOW"
		# On recupère tous les types qui sont entre crochets depuis le serveur de repos, et on retire tous les crochets pour les afficher plus clairement : 
		curl -s "https://URL-reposerver/linupdate.allconf" | grep "\[.*\]" | sed 's|\]\[|\n|g' | sed 's|\[||g' | sed 's|\]| |g'
		echo -e "$RESET"
	fi
done
while [ -z "$SERVER_ENV" ];do
	read -p " → Environnement : " SERVER_ENV
done

mkdir -p /root/scripts/linupdate/ &&
echo -e "# Fichier de conf de linupdate pour $HOSTNAME\n[CONFIGURATION]\nPROFILE=\"$PROFILE\"\nENV=\"$SERVER_ENV\"\nMAIL_RECIPIENT=\"\"\nALLOW_SELF_UPDATE=\"yes\"\n\n[SOFTWARE CONFIGURATION]\nEXCLUDE_MAJOR=\"\"\nEXCLUDE=\"\"\nNEED_RESTART=\"\"" > $CONF # Injection de la conf de base pour linupdate.conf
chmod 600 linupdate.conf 
echo -e "\n${GREEN}Configuration terminée${RESET}\n"