#!/usr/bin/env bash

# Vérifie si une nouvelle version de ce script est disponible sur github et l'installe
function selfUpdate
{
    # Si la mise à jour automatique n'est pas activé alors on quitte la fonction
    if [ "$ALLOW_SELF_UPDATE" != "yes" ];then
        return
    fi

    AVAILABLE_VERSION=$(curl -s "https://raw.githubusercontent.com/lbr38/linupdate/master/version")
    if [ -z "$AVAILABLE_VERSION" ];then
        echo -e "Checking new available release update: [$RED ERROR $RESET] while retrieving new available release version.\n"

    elif [ "$VERSION" != "$AVAILABLE_VERSION" ];then
        echo -e "${YELLOW}A new release version is available: ${AVAILABLE_VERSION}${RESET}"
        rm /tmp/linupdate -rf
        cd /tmp

        # Téléchargement de la nouvelle version :
        echo -ne " → Installating new release: " 
        if git clone --quiet https://github.com/lbr38/linupdate.git > /dev/null;then
            echo -e "[$GREEN OK $RESET]"
        else
            echo -e "[$RED ERROR $RESET] while downloading new release."
            (( UPDATE_ERROR++ ))
            clean_exit
        fi

        cd /tmp/linupdate
        rsync -a --quiet --delete-after functions/ ${BASE_DIR}/functions/
        rsync -a --quiet --delete-after mods-available/ ${BASE_DIR}/mods-available/
        rsync -a --quiet --delete-after service/ ${BASE_DIR}/service/
        rsync -a --quiet linupdate ${BASE_DIR}/
        rsync -a --quiet version ${BASE_DIR}/

        # Après une mise à jour de linupdate, il faut redémarrer l'agent si celui-ci est installé et démarré
        if [ -f "/etc/systemd/system/linupdate.service" ];then
            # Si le service est démarré, on le redémarre
            if systemctl is-active --quiet linupdate.service;then
                restartAgent
            fi
        fi

        echo -e " → Relaunching linupdate with the same parameters: $LINUPDATE_PARAMS"
        sleep 1

        # Si il n'y a pas d'argument à passer, on reéxécute le script sans paramètre
        if [ -z "$LINUPDATE_PARAMS" ];then 
            exec "$LINUPDATE"
        # Si il y a eu des paramètres, on reéxécute le script avec les mêmes paramètres.
        # Ne pas mettre $LINUPDATE_PARAMS entre quotes "" sinon les paramètres vont se réexécuter comme 1 seul paramètre et ne seront pas reconnus.
        else 
            exec "$LINUPDATE" $LINUPDATE_PARAMS
        fi
    else
        # Dans le cas où on a fait une demande de mise à jour seulement (paramètre --update), on affiche quand même un message pour avertir qu'aucune nouvelle version n'est disponible
        if [ "$ONLY_UPDATE" -eq "1" ];then
            echo -e "${YELLOW}No new available release.${RESET}"
        fi
    fi
}