#!/bin/bash
# Vérification que l'espace disque restant est suffisant pour effectuer la mise à jour (au moins 1Go d'espace)

echo -ne "\nEspace restant sur le serveur : "

SPACE_LEFT=$(df | egrep "/$" | awk '{print $4}')
if [ $SPACE_LEFT -lt 1000000 ];then
	echo -ne "${ROUGE}"; df -h | egrep "/$" | awk '{print $4}';	echo -ne "${RESET}"
	(( UPDATE_ERROR++ ))
	if [ "$MAIL_ALERT" -eq "1" ];then sendMail;fi
	clean_exit
else
		df -h | egrep "/$" | awk '{print $4}'
fi