#!/usr/bin/env bash
# Vérification que l'espace disque restant est suffisant pour effectuer la mise à jour (au moins 1Go d'espace)

function spaceLeft
{
    echo -ne "\nSpace left: "

    SPACE_LEFT=$(df | egrep "/$" | awk '{print $4}')
    if [ "$SPACE_LEFT" -lt 1000000 ];then
        echo -ne "${RED}"; df -h | egrep "/$" | awk '{print $4}';    echo -ne "${RESET}"
        (( UPDATE_ERROR++ ))
        if [ "$MAIL_ENABLED" -eq "true" ];then 
            sendMail
        fi
        clean_exit
        
    else
        df -h | egrep "/$" | awk '{print $4}'
    fi
}