#!/usr/bin/env bash

# Chargement des modules complémentaires si existent dans mods-enabled
# Ce chargement a pour but d'afficher à l'utilisateur quels modules sont activés pendant la mise à jour et de faire une première vérification de la conf du module avant de poursuivre

function loadModules
{
    if [ -d "$MODULES_ENABLED_DIR" ];then
        if [ "$(ls -A $MODULES_ENABLED_DIR)" ];then
            echo -e " Loading mods:"
            #cd "$MODULES_ENABLED_DIR"
            for MODULE in $(ls -A1 ${MODULES_ENABLED_DIR}/*.mod);do
                # Source de module.mod
                source "$MODULE"
                # Appel de la fonction mod_load à l'intérieur du fichier précédemment sourcé
                mod_load
            done

            echo ""
        fi
    fi
}