#!/usr/bin/env bash

function update
{
    # Si la vérification des paquets n'a trouvé aucun paquet à mettre à jour alors il est inutile d'exécuter les mises à jour
    # On sort de la fonction
    if [ "$SOMETHING_TO_UPDATE" == "no" ];then
        return
    fi

    # Fonction lançant les mises à jour yum
    {
        echo -e "\nUpdate is running..."

        echo -ne "Cleaning cache: "
        if [ "$OS_FAMILY" == "Redhat" ];then
            checkYumLock
            yum clean all -q
        fi
        if [ "$OS_FAMILY" == "Debian" ];then
            apt-get clean
        fi

        echo -e "[$GREEN OK $RESET]"

        # echo -e "\nInstallation des mises à jour :"

        # Si c'est du Debian, on charge la liste des paquets
        if [ "$OS_FAMILY" == "Debian" ];then
            apt-get -o Acquire::Check-Valid-Until=false -qq --allow-releaseinfo-change update
        fi

        # Si $UPDATE_EXCLUDE n'est pas vide, alors on exclu les paquets de la mise à jour
        if [ ! -z "$UPDATE_EXCLUDE" ];then
            if [ "$OS_FAMILY" == "Redhat" ];then
                YUM_OPTIONS+=" --exclude=${UPDATE_EXCLUDE}"
            fi
            if [ "$OS_FAMILY" == "Debian" ];then
                echo -e "\nExcluding critical packages: $YELLOW"

                IFS=' '
                for PACKAGE in ${UPDATE_EXCLUDE[@]};do # Attention ne pas placer de double quote sur cette variable
                    apt-mark hold "$PACKAGE"
                done

                echo -e "$RESET"
            fi
        fi

        # Updating packages
        if [ "$OS_FAMILY" == "Redhat" ];then
            yum $YUM_OPTIONS update -y
        fi
        if [ "$OS_FAMILY" == "Debian" ];then
            apt-get "$APT_UPGRADE" -y "$APT_OPTIONS"
        fi

        echo -e "\n${GREEN}Update completed${RESET}\n"

    # If one command fail    
    } || {
        echo -e "\n${YELLOW}Update has failed${RESET}"
        (( UPDATE_ERROR++ ))
    }
}