#!/bin/bash

# Si la vérification des paquets n'a trouvé aucun paquet à mettre à jour alors il est inutile d'exécuter les mises à jour
# On sort de la fonction
if [ "$UPDATE_EXEC" == "no" ];then
	return
fi

# Fonction lançant les mises à jour yum
{
	echo -e "\nMises à jour en cours..."
	echo -ne "Nettoyage du cache au préalable : "
	if [ "$OS_FAMILY" == "Redhat" ];then yum clean all -q;fi
	if [ "$OS_FAMILY" == "Debian" ];then apt-get clean;fi
	echo -e "[$GREEN OK $RESET]"

	echo -e "\nInstallation des mises à jour :"
	# Si c'est du Debian, on charge la liste des paquets
	if [ "$OS_FAMILY" == "Debian" ];then apt-get -o Acquire::Check-Valid-Until=false -qq --allow-releaseinfo-change update;fi

	# Si $UPDATE_EXCLUDE n'est pas vide, alors on exclu les paquets de la mise à jour
	if [ ! -z "$UPDATE_EXCLUDE" ];then
		if [ "$OS_FAMILY" == "Redhat" ];then yum --exclude=${UPDATE_EXCLUDE} update -y;fi
		if [ "$OS_FAMILY" == "Debian" ];then
			echo -e "\nExclusion des paquets critiques : $YELLOW"
			IFS=' ' # Dans $UPDATE_EXCLUDE le séparateur est un espace
			for PACKAGE in ${UPDATE_EXCLUDE[@]};do # Attention ne pas placer de double quote sur cette variable
				apt-mark hold "$PACKAGE"
			done
			echo -e "$RESET"
			# Puis on met à jour, plusieurs cas possible avec Debian : mise à jour normale ou dist-upgrade ; écrasement des fichiers de conf ou conservation 
			if   [ "$DIST_UPGRADE" -eq "1" ] && [ "$KEEP_OLDCONF" -eq "0" ];then apt-get dist-upgrade -y
			elif [ "$DIST_UPGRADE" -eq "1" ] && [ "$KEEP_OLDCONF" -eq "1" ];then apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade -y
			elif [ "$DIST_UPGRADE" -eq "0" ] && [ "$KEEP_OLDCONF" -eq "0" ];then apt-get upgrade -y
			elif [ "$DIST_UPGRADE" -eq "0" ] && [ "$KEEP_OLDCONF" -eq "1" ];then apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade -y
			fi
		fi
	else # Si $UPDATE_EXCLUDE est vide alors on met à jour normalement, sans exclusion
		if [ "$OS_FAMILY" == "Redhat" ];then yum update -y;fi
		if [ "$OS_FAMILY" == "Debian" ];then 
			# Plusieurs cas possible avec Debian : mise à jour normale ou dist-upgrade ; écrasement des fichiers de conf ou conservation 
			if   [ "$DIST_UPGRADE" -eq "1" ] && [ "$KEEP_OLDCONF" -eq "0" ];then apt-get dist-upgrade -y
			elif [ "$DIST_UPGRADE" -eq "1" ] && [ "$KEEP_OLDCONF" -eq "1" ];then apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade -y
			elif [ "$DIST_UPGRADE" -eq "0" ] && [ "$KEEP_OLDCONF" -eq "0" ];then apt-get upgrade -y
			elif [ "$DIST_UPGRADE" -eq "0" ] && [ "$KEEP_OLDCONF" -eq "1" ];then apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade -y
			fi
		fi
	fi &&
	echo -e "\nMises à jour terminées"
	
} || {	# Si une commande échoue
	echo -e "\nMises à jour échouées"
	(( UPDATE_ERROR++ ))	# On incrémente $UPDATE_ERROR
}
