#!/bin/bash

# Supprime la tâche cron après maj, si existe
if [ "$CONF_SOFT_KEEP_CRON" != "yes" ];then # On conserve uniquement la tâche cron si le paramètre est égal 'yes'. Dans tous les autres cas (!= yes) on supprime par sécurité
	# Il faut déjà déterminer le chemin de la crontab (différent selon si c'est Debian ou Redhat)
	if [ -f "/var/spool/cron/${USER}" ];then CRONTAB_PATH="/var/spool/cron/${USER}";fi
	if [ -f "/var/spool/cron/crontabs/${USER}" ];then CRONTAB_PATH="/var/spool/cron/crontabs/${USER}";fi
	
	if grep -q "linupdate" "${CRONTAB_PATH}";then
		echo -ne "Suppression de la tâche cron en place : "
		sed -i '/linupdate/d' "${CRONTAB_PATH}" &&
		echo -e "[$VERT OK $RESET]"
	fi
fi