#!/bin/bash

# Exécution de modules complémentaires post-mise à jour

if [ -d "$MODULES_ENABLED_DIR" ];then
    if [ "$(ls -A $MODULES_ENABLED_DIR)" ];then
        echo -e " Execution des modules post-mise à jour"

        for MODULE in $(ls -A1 ${MODULES_ENABLED_DIR});do
            # On récupère le nom exact du module (sans le .mod)
            MODULE_FORMATTED=$(echo "${MODULE%.mod}")

            # Si le module fait parti des modules chargés par loadModules alors on peut charger son code
            if printf '%s\n' "${LOADED_MODULES[@]}" | grep -q "^${MODULE_FORMATTED}$";then
                # On charge le code du module et on exécute sa fonction pre-mise à jour (pre)
                source "${MODULES_ENABLED_DIR}/${MODULE}"
                post
            fi
        done
    fi
fi