#!/usr/bin/env bash
# Redémarrage des services post-mise à jour

function restartService
{
    # Si $SERVICE_TO_BE_RESTARTED contient des services nécessitant un redémarrage, on traite
    if [ ! -z "$SERVICE_TO_BE_RESTARTED" ];then
        OLD_IFS="$IFS"
        IFS=$','

        for SERVICE in $SERVICE_TO_BE_RESTARTED; do
            echo -ne "→ Restarting ${YELLOW}${SERVICE}${RESET} service: "
            systemctl restart "$SERVICE" --quiet
            if [ "$?" != "0" ];then
                echo -e "[$YELLOW ERROR $RESET] while restarting"
            else
                echo -e "[$GREEN OK $RESET]"
            fi
        done

        IFS=$OLD_IFS
    fi
}