#!/bin/bash
# Redémarrage des services post-mise à jour

function restartService
{
    # Si $SERVICE_TO_BE_RESTARTED contient des services nécessitant un redémarrage, on traite
    if [ ! -z "$SERVICE_TO_BE_RESTARTED" ];then
        IFS=" ";

        for SERVICE in $SERVICE_TO_BE_RESTARTED; do
            echo -ne "→ Redémarrage du service ${YELLOW}${SERVICE}${RESET} : "
            systemctl restart "$SERVICE" --quiet
            if [ "$?" != "0" ];then
                echo -e "[$YELLOW ERREUR $RESET] lors du redémarrage du service"
            else
                echo -e "[$GREEN OK $RESET]"
            fi
        done
    fi
}