#!/bin/bash

if [ "$MAIL_ENABLED" == "yes" ];then
	# Avant toute chose, on supprime les codes couleurs ANSI dans le fichier de log, ils sont utiles pour afficher de la couleur dans le terminal mais ils polluent le rapport mail qui devient illisible :
	sed 's/\x1b\[[0-9;]*m//g' "$LOG" > "$LOG_RAPPORT_MAIL"

	echo -ne "→ Envoi du rapport de mise à jour par mail : "

	if [ "$MOD_ERROR" -gt "0" ];then
		echo "Erreur lors de l'exécution d'un module" | mutt -s "[ ERREUR ] Mise à jour échouée - $HOSTNAME - $DATE_FULL - linupdate" -a "$LOG_RAPPORT_MAIL" -- $MAIL_RECIPIENT
	fi

	if [ ! -z "$MAJ_EXCLUDE" ];then
		echo "Des paquets critiques ont été détectés. Ils ont été exclus de la mise à jour. Voir le rapport de mises à jour en pièce jointe." | mutt -s "[WARNING] Mise à jour effectuée mais paquet(s) critique(s) ignoré(s) - $HOSTNAME - $DATE_FULL - linupdate" -a "$LOG_RAPPORT_MAIL" -- $MAIL_RECIPIENT
	elif [ ! -z "$MAJ_EXCLUDE" ] && [ "$UPDATE_ERROR" -gt "0" ];then
		echo "Des paquets critiques ont été détectés. Ils ont été exclus de la mise à jour (échouée). Voir le rapport de mises à jour en pièce jointe." | mutt -s "[ERREUR & WARNING] Mise à jour en erreur et paquet(s) critique(s) ignoré(s) - $HOSTNAME - $DATE_FULL - linupdate" -a "$LOG_RAPPORT_MAIL" -- $MAIL_RECIPIENT
	elif [ "$UPDATE_ERROR" -gt "0" ];then
		# Si il y eu des erreurs pendant la mise à jour, alors on l'indique dans le titre du rapport
		echo "Rapport de mises à jour en pièce jointe" | mutt -s "[ ERREUR ] Mise à jour échouée - $HOSTNAME - $DATE_FULL - linupdate" -a "$LOG_RAPPORT_MAIL" -- $MAIL_RECIPIENT
	else
		# Sinon titre normal
		echo "Rapport de mises à jour en pièce jointe" | mutt -s "[ OK ] Mise à jour - $HOSTNAME - $DATE_FULL - linupdate" -a "$LOG_RAPPORT_MAIL" -- $MAIL_RECIPIENT
	fi

	echo -e "[$VERT OK $RESET]"
fi