#!/usr/bin/env bash

function sendMail
{
    if [ "$MAIL_ENABLED" == "yes" ];then
        # Avant toute chose, on supprime les codes couleurs ANSI dans le fichier de log, ils sont utiles pour afficher de la couleur dans le terminal mais ils polluent le rapport mail qui devient illisible :
        sed 's/\x1b\[[0-9;]*m//g' "$LOG" > "$LOG_REPORT_MAIL"

        echo -ne "→ Sending update mail report: "

        if [ "$MOD_ERROR" -gt "0" ];then
            echo "Error while executing module" | mutt -s "[ ERROR ] Update has failed - $HOSTNAME - $DATE_DMY at $TIME - linupdate" -a "$LOG_REPORT_MAIL" -- $MAIL_RECIPIENT
        fi

        if [ ! -z "$UPDATE_EXCLUDE" ];then
            echo "Critical packages have been detected. They have been excluded from update. Check attached update report." | mutt -s "[ WARNING ] Update completed but critical packages update have been ignored - $HOSTNAME - $DATE_DMY at $TIME - linupdate" -a "$LOG_REPORT_MAIL" -- $MAIL_RECIPIENT
        elif [ ! -z "$UPDATE_EXCLUDE" ] && [ "$UPDATE_ERROR" -gt "0" ];then
            echo "Critical packages have been detected. They have been excluded from failed update. Check attached update report." | mutt -s "[ ERROR & WARNING ] Update failed and critical packages excluded - $HOSTNAME - $DATE_DMY at $TIME - linupdate" -a "$LOG_REPORT_MAIL" -- $MAIL_RECIPIENT
        elif [ "$UPDATE_ERROR" -gt "0" ];then
            # Si il y eu des erreurs pendant la mise à jour, alors on l'indique dans le titre du rapport
            echo "Update report is attached" | mutt -s "[ ERROR ] Update failed - $HOSTNAME - $DATE_DMY at $TIME - linupdate" -a "$LOG_REPORT_MAIL" -- $MAIL_RECIPIENT
        else
            # Sinon titre normal
            echo "Update report is attached" | mutt -s "[ OK ] Update completed - $HOSTNAME - $DATE_DMY at $TIME - linupdate" -a "$LOG_REPORT_MAIL" -- $MAIL_RECIPIENT
        fi

        echo -e "[$GREEN OK $RESET]"
    fi
}