#!/usr/bin/env bash

function deployAgent
{
    SERVICE_FILE="/etc/systemd/system/linupdate.service"
    AGENT_FILE="/opt/linupdate/service/linupdate-agent"

    if [ ! -d "/etc/systemd/system/" ];then
        echo -e "/etc/systemd/system/ directory does not exist"
        return
    fi

    # man systemd.service
    echo "[Unit]
    Description=linupdate-agent

    [Service]
    Type=simple
    ExecStart=/opt/linupdate/service/linupdate-agent
    #CPUQuota=50%

    [Install]
    WantedBy=multi-user.target" > "$SERVICE_FILE"

    systemctl daemon-reload

    chmod 500 "$AGENT_FILE"

    echo -e "${YELLOW}Agent deployed${RESET}"

    echo -ne "\nActivate ${YELLOW}linupdate${RESET} agent on boot? (yes/no): ";read -p "" CONFIRM
    if [ "$CONFIRM" == "yes" ];then 
        enableAgent
    fi

    echo -ne "\nStart ${YELLOW}linupdate${RESET} agent now? (yes/no): ";read -p "" CONFIRM
    if [ "$CONFIRM" == "yes" ];then 
        startAgent
    fi
}