#!/bin/bash

function deployAgent
{
    SERVICE_FILE="/etc/systemd/system/linupdate.service"
    AGENT_FILE="/opt/linupdate/service/linupdate-agent"

    if [ ! -d "/etc/systemd/system/" ];then
        echo -e "Le répertoire /etc/systemd/system/ n'existe pas"
        return
    fi

    # man systemd.service
    echo "[Unit]
    Description=linupdate-agent

    [Service]
    Type=simple
    ExecStart=/opt/linupdate/service/linupdate-agent
    #CPUQuota=50%

    [Install]
    WantedBy=multi-user.target" > "$SERVICE_FILE"

    systemctl daemon-reload

    chmod 500 "$AGENT_FILE"

    echo -e "${YELLOW}Agent déployé${RESET}"

    echo -ne "\nActiver l'agent ${YELLOW}linupdate${RESET} au démarrage du système ? (yes/no) : ";read -p "" CONFIRM
    if [ "$CONFIRM" == "yes" ];then 
        enableAgent
    fi

    echo -ne "\nDémarrer l'agent ${YELLOW}linupdate${RESET} maintenant ? (yes/no) : ";read -p "" CONFIRM
    if [ "$CONFIRM" == "yes" ];then 
        startAgent
    fi
}