#!/usr/bin/env bash

export LC_ALL="en_US.UTF-8"
export TERM="xterm-256color"
# export COLUMNS=190
cd "/home"

## ↓ VARIABLES ↓ ##
BASE_DIR="/opt/linupdate"
DATE_DMY=$(date +%d-%m-%Y)                          # Today date in 'DD-MM-YYYY' format
DATE_YMD=$(date +%Y-%m-%d)                          # Today date in 'YYYY-MM-DD' format
DATE_FULL=$(date +%d-%m-%Y_%Hh%M)                   # Today date in 'DD-MM-YYYY_hh-mm' format
TIME=$(date +%Hh%M)                                 # Time in '00h00' format
TIME_FULL=$(date +%Hh%Mm%Ss)                        # Time in '00h00m00s' format
LINUPDATE="${BASE_DIR}/linupdate"                   # Main program
FUNCTIONS="${BASE_DIR}/functions"                   # Functions directory
LOGS_DIR="/var/log/linupdate"                       # Logs directory
ETC_DIR="/etc/linupdate"                            # Configuration files directory
CONF="${ETC_DIR}/linupdate.conf"                    # Main configuration file
MODULES_DIR="${BASE_DIR}/mods-available"            # Available modules directory
MODULES_ENABLED_DIR="${BASE_DIR}/mods-enabled"      # Enabled modules directory
AGENTS_ENABLED_DIR="${BASE_DIR}/agents-enabled"     # Enabled agents directory
MODULES_CONF_DIR="${ETC_DIR}/modules"               # Modules configuration files directory
SERVICE_DIR="${BASE_DIR}/service"                   # Main agent/service directory
LINUPDATE_PARAMS="$@"
OS_NAME=""
OS_ID=""
OS_VERSION=""
OS_FAMILY=""
KERNEL=$(uname -r)
ARCH=$(uname -m)
VIRT_TYPE=""
PKG_MANAGER=""
PKG_TYPE=""
PROFILE=""
SERVER_ENV=""
FAILLEVEL=""
MAIL_ENABLED=""
MAIL_RECIPIENT=""
CONF_SOFT_EXCLUDE_MAJOR=""
CONF_SOFT_EXCLUDE=""
CONF_SOFT_NEED_RESTART=""
HISTORIQUE="${BASE_DIR}/linupdate.history"                     # Packages updates history file
REPORT="${DATE_YMD}_${TIME_FULL}_linupdate_${HOSTNAME}.log"    # Name of the log/report file
LOG="${LOGS_DIR}/${REPORT}"                                    # Location of the log/report file
LOG_REPORT_MAIL="/tmp/${REPORT}"                               # Same file but this one will be formated to be sent by mail (without ANSI characters)
APT_UPGRADE="upgrade"                                          # upgrade or dist-upgrade (default: upgrade)
APT_OPTIONS=""
YUM_OPTIONS=""
KEEP_OLDCONF="0"
UPDATE_ERROR="0"
SOMETHING_TO_UPDATE="yes"
ONLY_CHECK_UPDATE="false"
IGNORE_EXCLUDE="0"
UPDATE_EXCLUDE=""
SERVICE_TO_BE_RESTARTED=""
READ_PACKAGES_TO_EXCLUDE=""
READ_PACKAGES_TO_EXCLUDE_MAJOR=""
CRONTAB_PATH=""
ERROR_STATUS="0"
ASSUME_YES="0"
ONLY_UPDATE="0"
PROCID=$(echo "$RANDOM")
VERBOSE="0"
FROM_AGENT="0"

# Mods variables
MOD_ERROR="0"
LOADED_MODULES=""

# Terminal printing
# Colors:
WHITE=$(tput setaf 7)
GRAY=$(tput setaf 8)
GREEN=$(tput setaf 2)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
CYAN=$(tput setaf 6)
RESET=$(tput sgr0)
# Bold version:
WHITEB=$(tput bold;tput setaf 7)
GRAYB=$(tput bold;tput setaf 8)
GREENB=$(tput bold;tput setaf 2)
REDB=$(tput bold;tput setaf 1)
YELLOWB=$(tput bold;tput setaf 3)
CYANB=$(tput bold;tput setaf 6)
# Separator
SEP=$(printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' '=')

# Retrieve actual version
if [ -f "${BASE_DIR}/version" ];then
    VERSION=$(cat ${BASE_DIR}/version)
else
    VERSION=""
fi

# Detecting user
if [ "$(id -u)" -ne "0" ];then
    echo -e "\n${YELLOW}Must be executed with sudo ${RESET}\n"
    exit
fi

# Create some base directories
mkdir -p "$ETC_DIR"
mkdir -p "$MODULES_CONF_DIR"
mkdir -p "$MODULES_DIR"
mkdir -p "$MODULES_ENABLED_DIR"
mkdir -p "$AGENTS_ENABLED_DIR"
mkdir -p "$SERVICE_DIR"


## ↓ FONCTIONS ↓ ##

# Print available parameters
help() {
    echo -e "Available parameters:\n"
    echo -e " Main:"
    echo -e "  --vv|-vv                                     → Enable verbose mode"
    echo -e "  --version|-v                                 → Print current version"
    echo -e "  --update|-u                                  → Update linupdate to the last available release on github"
    echo -e "  --enable-auto-update                         → Enable linupdate automatic update"
    echo -e "  --disable-auto-update                        → Disable linupdate automatic update"
    echo -e "  --install|--reinstall|-i                     → Install or reinstall linupdate (/!\ will delete actual configuration)"
    echo -e "  --profile|--type|--print-profile PROFILE     → Configure host profile (leave empty to print actual)"
    echo -e "  --environment|--env ENV                      → Configure host environment (leave empty to print actual)"
    echo -e ""
    echo -e " Package update configuration"
    echo -e "  --exclude-major|-em PACKAGE                  → Configure packages to exclude on major release update, separated by a comma. Specify 'none' to clean."
    echo -e "  --exclude|-e PACKAGE                         → Configure packages to exclude, separated by a comma. Specify 'none' to clean."
    echo -e ""
    echo -e " Update execution"
    echo -e "  --check-updates|-cu                          → Check packages to be updated and quit"
    echo -e "  --assume-yes|--force                         → Enable 'assume yes' (answer 'yes' to every confirm prompt)"
    echo -e "  --dist-upgrade|-du                           → Enable 'dist-upgrade' for apt (Debian only)"
    echo -e "  --keep-oldconf|-ko                           → Keep actual configuration file when attempting to be overwrited by apt during package update (Debian only)"
    echo -e "  --ignore-exclude|-ie                         → Ignore all packages minor or major release update exclusions"
    echo -e ""
    echo -e " Modules"
    echo -e "  --list-modules|--list-mod|-m                 → List available modules"
    echo -e "  --mod-enable|-mod-enable|-me MODULE          → Enable specified module"
    echo -e "  --mod-disable|-mod-disable|-md MODULE        → Disable specified module"
    echo -e "  --mod-configure|-mc|--mod-exec MODULE        → Configure specified module (using module commands, see module help or documentation)"
    echo -e "  --mod-configure MODULE --help                → Print module help"
    echo -e ""
    echo -e " Agent"
    echo -e "  --agent-deploy|--deploy-agent                → Deploy linupdate agent"
    echo -e "  --agent-start|--start-agent                  → Start linupdate agent"
    echo -e "  --agent-stop|--stop-agent                    → Stop linupdate agent"
    echo -e "  --agent-restart|--restart-agent              → Restart linupdate agent"
    echo -e "  --agent-enable|--enable-agent                → Enable linupdate agent start on boot"
    echo -e ""
}

# Install linupdate files and directories
selfInstall() {
    # Clean /opt/linupdate
    rm "$BASE_DIR" -rf

    # Get linupdate from github
    rm -rf /tmp/linupdate
    git clone --quiet https://github.com/lbr38/linupdate.git /tmp/linupdate > /dev/null &&

    # Create functions dir
    mkdir -p "$FUNCTIONS"

    # Copy functions
    \cp -r /tmp/linupdate/functions ${BASE_DIR}/

    # Copy modules
    \cp -r /tmp/linupdate/mods-available ${BASE_DIR}/

    # Copy service
    \cp -r /tmp/linupdate/service ${BASE_DIR}/

    # Copy linupdate itself
    \cp /tmp/linupdate/linupdate ${BASE_DIR}/

    # Version
    cp /tmp/linupdate/version ${BASE_DIR}/version

    # Create a linupdate symlink inside /usr/bin/
    rm /usr/bin/linupdate -f
    ln -s ${BASE_DIR}/linupdate /usr/bin/linupdate

    # Set permissions on main script
    chmod 700 ${BASE_DIR}/linupdate

    # Restart linupdate
    exec "${BASE_DIR}/linupdate"
}

# Loading all functions from functions dir
if [ -d "$FUNCTIONS" ];then

    # Sourcing all files inside functions dir
    for FUNCTION_FILE in $(ls -A1 "$FUNCTIONS");do
        source "$FUNCTIONS/$FUNCTION_FILE"
    done
fi

## 1. If /opt/linupdate does not exist then process first installation
if [ ! -d "$BASE_DIR" ] || [ ! -d "$BASE_DIR/functions" ];then
    # selfInstall will copy all necessary files to /opt/linupdate from linupdate's git main branch
    selfInstall
    
    # Install dependencies
    checkDependencies
fi

# Check that system is valid before continue
checkSystem

## 2. If no configuration file exists in /etc/linupdate/linupdate.conf then launch linupdate configuration
if [ ! -f "$CONF" ];then
    mkdir -p "$ETC_DIR"
    configure
fi


## ↓ EXECUTION ↓ ##

# Params pre-check
# If --from-agent param is passed, then rewrite output log filename and make it hidden
if echo "$@" | grep -q "\-\-from\-agent";then
    REPORT=".${DATE_YMD}_${TIME_FULL}_linupdate_${HOSTNAME}-agent.log"
    LOG="${LOGS_DIR}/${REPORT}"
fi

# Create logs dir if not exist
mkdir -p "$LOGS_DIR"

# Create/clean logfile
echo -n> "$LOG"
chmod 660 "$LOG"

# Writing everything happening to the log file
exec &> >(tee -a "$LOG")

# Detect virtualization type
if [ -f "/usr/sbin/virt-what" ];then
    VIRT_TYPE=$(/usr/sbin/virt-what)
    if [ -z "$VIRT_TYPE" ];then
        VIRT_TYPE="Bare metal"
    fi
fi

set +u

while [ $# -ge 1 ];do
    case "$1" in
        --help|-h)
            help
            clean_exit
        ;;
        --version|-v|-V)
            echo "Version: ${YELLOW}$VERSION${RESET}"
            clean_exit
        ;;
        -vv|--vv)
            VERBOSE="1"
        ;;
        --force|--assume-yes)
            ASSUME_YES="1"
        ;;
        --profile|--type)
            # If nothing has been specified then print actual profile
            if [ -z "$2" ];then
                PROFILE=$(grep "^PROFILE=" $CONF | sed 's/PROFILE=//g' | sed 's/"//g')
                echo -e "Current profile: ${YELLOW}$PROFILE${RESET}"
            else
                # If a profile name has been specified then replace actual profile with it
                if grep -q "PROFILE=" $CONF;then
                    sed -i "s/PROFILE=.*/PROFILE=\"$2\"/g" $CONF &&
                    echo -e "Profil has been changed: ${YELLOW}$2${RESET}"
                fi
            fi
            clean_exit
        ;;
        --environment|--env)
            # If nothing has been specified then print actual env
            if [ -z "$2" ];then
                ENV=$(grep "^ENV=" $CONF | sed 's/ENV=//g' | sed 's/"//g')
                echo -e "Current environment: ${YELLOW}$ENV${RESET}"
            else
                # If an env name has been specified then replace actual env with it
                if grep -q "ENV=" $CONF;then
                    sed -i "s/ENV=.*/ENV=\"$2\"/g" $CONF &&
                    echo -e "Environment has been changed: ${YELLOW}$2${RESET}"
                fi
            fi
            clean_exit
        ;;
        --update|-u)
            ONLY_UPDATE="1"
            getConf
            selfUpdate
            clean_exit
        ;;
        --install|--reinstall|-i)
            if [ -d "/opt/linupdate" ];then
                echo -n " This action will delete the entire actual linupdate installation and its modules. Confirm (yes/no): "; read -p "" CONFIRM
                if [ "$CONFIRM" != "yes" ];then
                    clean_exit
                fi
                rm ${BASE_DIR} -rf
            fi
            selfInstall
            clean_exit
        ;;
        --list-modules|--list-mod|-m)
            listModules
            clean_exit
        ;;
        --ignore-exclude|-ie)
            IGNORE_EXCLUDE=1
        ;;
        --check-updates|-cu)
            ONLY_CHECK_UPDATE="true"
            getConf
            checkPackagesBeforeUpdate
            clean_exit
        ;;
        --dist-upgrade|-du)
            APT_UPGRADE="dist-upgrade"
        ;;
        --keep-oldconf|-ko)
            export DEBIAN_FRONTEND="noninteractive"
            APT_OPTIONS='-o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"'
        ;;
        --exclude|-e)
            if [ ! -z "$2" ];then
                READ_PACKAGES_TO_EXCLUDE="$2"
            fi
            exclude
            clean_exit
        ;;
        --exclude-major|-em)
            if [ ! -z "$2" ];then
                READ_PACKAGES_TO_EXCLUDE="$2"
            fi
            READ_PACKAGES_TO_EXCLUDE_MAJOR="1"
            exclude
            clean_exit
        ;;
        --mod-enable|-mod-enable|-me)
            MODULE=$2
            shift
            if [ ! -f "${MODULES_DIR}/${MODULE}.mod" ];then
                echo "Error: unknown module ${YELLOW}${MODULE}${RESET}"
                clean_exit
            fi

            # Enable module
            source "${MODULES_DIR}/${MODULE}.mod"
            mod_enable &&
            echo -e "Module ${YELLOW}${MODULE}${RESET} enabled"
            clean_exit
        ;;
        --mod-disable|-mod-disable|-md)
            MODULE=$2
            shift
            if [ ! -f "${MODULES_DIR}/${MODULE}.mod" ];then
                echo "Error: unknown module ${YELLOW}${MODULE}${RESET}"
                clean_exit
            fi

            # Disable module
            source "${MODULES_DIR}/${MODULE}.mod"
            mod_disable &&
            echo -e "Module ${YELLOW}${MODULE}${RESET} disabled"
            clean_exit
        ;;
        --mod-configure|-mc|--mod-exec)
            getConf
            MODULE=$2
            shift
            if [ ! -f "${MODULES_DIR}/${MODULE}.mod" ];then
                echo "Error: unknown module ${YELLOW}${MODULE}${RESET}"
                clean_exit
            fi

            # Configure module
            source "${MODULES_DIR}/${MODULE}.mod"
            mod_configure $@ &&
            echo -e "Module ${YELLOW}${MODULE}${RESET} configured"
            clean_exit
        ;;
        --agent-deploy|--deploy-agent)
            deployAgent
            clean_exit
        ;;
        --agent-start|--start-agent)
            startAgent
            clean_exit
        ;;
        --agent-stop|--stop-agent)
            stopAgent
            clean_exit
        ;;
        --agent-restart|--restart-agent)
            restartAgent
            clean_exit
        ;;
        --agent-enable|--enable-agent)
            enableAgent
            clean_exit
        ;;
        --agent-disable|--disable-agent)
            disableAgent
            clean_exit
        ;;
        --from-agent)
            FROM_AGENT="1"
        ;;
        --enable-auto-update)
            enableSelfUpdate
            clean_exit
        ;;
        --disable-auto-update)
            disableSelfUpdate
            clean_exit
        ;;
        *)
            echo "Unknown parameter: $1"
            help
            clean_exit
        ;;
    esac
    shift
done

echo -e "\n\n
 .__  .__                        .___       __          
 |  | |__| ____  __ ________   __| _/____ _/  |_  ____  
 |  | |  |/    \|  |  \____ \ / __ |\__  \\   __\/ __ \ 
 |  |_|  |   |  \  |  /  |_> > /_/ | / __ \|  | \  ___/ 
 |____/__|___|  /____/|   __/\____ |(____  /__|  \___  >
              \/      |__|        \/     \/          \/ 


 ${YELLOW}linupdate${RESET} - advanced package updater for linux distributions\n\n"

# Checking dependencies
checkDependencies

# Reading configuration file
getConf

# Check if a new linupdate release is available and update (if auto-update enabled)
selfUpdate

# Loading modules
loadModules

# Execute pre-update modules
execPreModules

echo -e " Hostname:                     ${YELLOW}${HOSTNAME}${RESET}"
echo -e " OS:                           ${YELLOW}${OS_NAME} $OS_VERSION ${RESET}"
echo -e " Kernel:                       ${YELLOW}$KERNEL${RESET}"
if [ ! -z "$VIRT_TYPE" ];then
    echo -e " Virtualization:               ${YELLOW}${VIRT_TYPE}${RESET}"
fi
echo -e " Profile:                      ${YELLOW}${PROFILE}${RESET}"
echo -e " Environment:                  ${YELLOW}${SERVER_ENV}${RESET}"
echo -e " Executed on:                  ${YELLOW}${DATE_DMY} at ${TIME}${RESET}"
echo -ne " Executed by:                 ${YELLOW} "; whoami; echo -ne "${RESET}"
echo -ne " Execution method: "
if [ "$FROM_AGENT" == "1" ];then
    echo -e "            ${YELLOW}from linupdate agent${RESET}"
else
    if [ -t 0 ];then
        echo -e "            ${YELLOW}manual${RESET}"
    else
        echo -e "            ${YELLOW}automatic (no tty)${RESET}"
    fi
fi

# Check if some packages need to be excluded
checkPackagesBeforeUpdate

# Execute packages update
update

# Reactivate holded packages by apt-mark
if [ "$OS_FAMILY" == "Debian" ];then
    HOLDED_PACKAGES=$(apt-mark showhold)
    if [ ! -z "$HOLDED_PACKAGES" ];then
        OLD_IFS="$IFS"
        IFS=$'\n'
        for HOLDED_PACKAGE in $(echo "$HOLDED_PACKAGES");do
            apt-mark unhold "$HOLDED_PACKAGE"
        done
        IFS="$OLD_IFS"
    fi
fi

# Check if a system reboot is required
checkRebootNeeded

# Execute post-update modules
execPostModules

# Restarting services
restartService

echo -e "\nOperation completed\n" 

# Sending mail report
sendMail

clean_exit