#!/bin/bash
trap 'kill 0' EXIT

REPOSERVER_CONF="/etc/linupdate/modules/reposerver.conf"
INOTIFY_RUNNING="no"
NGREP_RUNNING="no"

while true; do

## Vérifications ##

    # Vérification de l'activation du module reposerver
    if [ ! -f "/opt/linupdate/mods-enabled/reposerver.mod" ];then
        echo -e "[ ERREUR ] Le module reposerver n'est pas activé"
        exit 1
    fi

    # Vérification de la présence d'un fichier de configuration pour le module reposerver
    if [ ! -f "$REPOSERVER_CONF" ];then
        echo -e "[ ERREUR ] Aucun fichier de configuration n'a été trouvé : '$REPOSERVER_CONF'"
        exit 1
    fi

    # Vérification de la présence d'un fichier de log pour yum ou dpkg
    if [ -f "/var/log/yum.log" ];then
        LOGFILE="/var/log/yum.log"

    elif [ -f "/var/log/apt/history.log" ];then
        LOGFILE="/var/log/apt/history.log"

    else
        echo -e "[ ERREUR ] Aucun fichier de log pour dpkg ou yum n'a été trouvé sur cet hôte"
        exit 1
    fi

## Récupération d'informations ##

    REPOSERVER_IP=$(grep "^IP=" "$REPOSERVER_CONF" | sed 's/IP=//g' | sed 's/"//g')
    if [ -z "$REPOSERVER_IP" ];then
        echo -e "[ ERREUR ] Impossible de déterminer l'adresse IP du serveur Repomanager"
        exit 1
    fi

    # Si aucun process inotify ne tourne, on le lance en background
    if [ "$INOTIFY_RUNNING" == "no" ];then
        # Si le fichier de log de apt ou yum est modifié alors on lance l'envoi de l'historique au serveur repomanager
        while true; do
            /usr/bin/inotifywait -q -e modify "$LOGFILE"
            echo "De nouveaux évènements ont été détectés dans '$LOGFILE' - envoi de l'historique au serveur repomanager."

            # Exécution
            # /opt/linupdate --mod-configure reposerver --send-full-history 2
            sleep 5
        done &

        INOTIFY_RUNNING="yes"
    fi

    # Surveillance des demandes de mise à jour en provenance du serveur Repomanager
    if [ "$NGREP_RUNNING" == "no" ];then
        while true; do
            /usr/bin/ngrep -q -t -W byline 'update-requested' "src host $REPOSERVER_IP" -n 1

            echo "Une demande de mise à jour a été émise du serveur repomanager"
            echo "Exécution de la mise à jour"

            # Exécution de la mise à jour
            # /opt/linupdate --force
            sleep 5
        done &

        NGREP_RUNNING="yes"
    fi

    # Envoi régulier des paquets disponibles pour mise à jour

    # Envoi regulier de tout l'historique des évènements passés sur cet hôte


    sleep 5
done

exit 0