#!/bin/bash

SERVICE="/opt/linupdate/service.py"

# Restore configuration files if exists
if [ -f "/tmp/linupdate.yml.debsave" ];then
    rm -f /etc/linupdate/linupdate.yml
    mv /tmp/linupdate.yml.debsave /etc/linupdate/linupdate.yml
fi
if [ -f "/tmp/update.yml.debsave" ];then
    rm -f /etc/linupdate/update.yml
    mv /tmp/update.yml.debsave /etc/linupdate/update.yml
fi

# If no configuration files exists, copy default
if [ ! -f "/etc/linupdate/linupdate.yml" ];then
    cp /opt/linupdate/templates/linupdate.template.yml /etc/linupdate/linupdate.yml
fi
if [ ! -f "/etc/linupdate/update.yml" ];then
    cp /opt/linupdate/templates/update.template.yml /etc/linupdate/update.yml
fi

# Create a symlink to main script
ln -sf /opt/linupdate/linupdate.py /usr/bin/linupdate

# Install en_US.UTF-8 locale if not present
if ! locale -a | grep -q "en_US.UTF-8";then
    apt-get install locales-all -y > /dev/null
fi

# Set permissions
chmod 750 /etc/linupdate
chmod 750 /opt/linupdate

# Only if systemd is installed (not the case on github runners)
if [ -f "/usr/bin/systemctl" ];then
    # Copy systemd unit file if not exists
    if [ ! -f "/lib/systemd/system/linupdate.service" ];then
        cp /opt/linupdate/templates/linupdate.systemd.template /lib/systemd/system/linupdate.service
    fi

    # Replace systemd unit file if some options are missing
    if  ! grep -q "^CPUQuota"       /lib/systemd/system/linupdate.service || \
        ! grep -q "^CPUWeight"      /lib/systemd/system/linupdate.service || \
        ! grep -q "^MemoryMax"      /lib/systemd/system/linupdate.service || \
        ! grep -q "^OOMScoreAdjust" /lib/systemd/system/linupdate.service;
    then
        \cp /opt/linupdate/templates/linupdate.systemd.template /lib/systemd/system/linupdate.service
    fi

    chmod 550 "$SERVICE"
    chown root:root "$SERVICE"

    # Clean old directories
    rm /opt/linupdate/agents-enabled -rf
    rm /opt/linupdate/mods-enabled -rf
    rm /opt/linupdate/mods-available -rf
    rm /opt/linupdate/service -rf

    /usr/bin/systemctl enable linupdate
    /usr/bin/systemctl --quiet daemon-reload

    # Restart or start service
    if /usr/bin/systemctl is-active --quiet linupdate;then
        # Do not restart if there is a /tmp/linupdate.restart-needed file, the service will restart itself
        if [ ! -f "/tmp/linupdate.restart-needed" ];then
            /usr/bin/systemctl restart --quiet linupdate
        fi
    else
        /usr/bin/systemctl start --quiet linupdate
    fi
fi