#!/bin/bash

DATA_DIR="/opt/linupdate"
SERVICE="$DATA_DIR/service/linupdate-agent"

# Restore configuration file if exists
if [ -f "/tmp/linupdate.conf.debsave" ];then
    rm -f /etc/linupdate/linupdate.conf
    mv /tmp/linupdate.conf.debsave /etc/linupdate/linupdate.conf
fi

# Create a symlink to main script
ln -sf /opt/linupdate/linupdate /usr/bin/linupdate

# Install en_US.UTF-8 locale if not present
if ! locale -a | grep -q "en_US.UTF-8";then
    apt-get install locales-all -y > /dev/null
fi

# Set permissions
chmod 750 /etc/linupdate
chmod 750 /opt/linupdate

# Only if systemd is installed (not the case on github runners)
if [ -f "/usr/bin/systemctl" ];then

    # Enable service script by creating a symlink
    ln -sf /lib/systemd/system/linupdate.service /etc/systemd/system/linupdate.service
    chmod 550 "$SERVICE"
    chown root:root "$SERVICE"

    /usr/bin/systemctl --quiet daemon-reload

    # Start service
    if /usr/bin/systemctl is-active --quiet linupdate;then
        /usr/bin/systemctl restart --quiet linupdate
    else
        /usr/bin/systemctl start --quiet linupdate
    fi
fi