#!/bin/bash

# Save current configuration files if exists
if [ -f "/etc/linupdate/linupdate.yml" ];then
    cp /etc/linupdate/linupdate.yml /tmp/linupdate.yml.debsave
fi
if [ -f "/etc/linupdate/update.yml" ];then
    cp /etc/linupdate/update.yml /tmp/update.yml.debsave
fi

# Only if systemd is installed (not the case on github runners)
if [ -f "/usr/bin/systemctl" ];then
    # Stop service if started
    if /usr/bin/systemctl is-active --quiet linupdate;then
        /usr/bin/systemctl stop --quiet linupdate
    fi
fi
