#!/usr/bin/env bash

function exclude
{
    # Si les paquets à exclure n'ont pas été précisé en paramètre, on les demande
    if [ -z "$READ_PACKAGES_TO_EXCLUDE" ];then
        echo -ne "Specify packages to exclude (separated by a comma): "; read -p "" READ_PACKAGES_TO_EXCLUDE
    fi

    # Suppression des éventuels espaces vides
    READ_PACKAGES_TO_EXCLUDE=$(echo "$READ_PACKAGES_TO_EXCLUDE" | sed 's/ //g')

    # Si la valeur renseignée est "none" alors on supprime l'exclusion en place
    if [ "$READ_PACKAGES_TO_EXCLUDE" == "none" ];then
        READ_PACKAGES_TO_EXCLUDE=""
    fi

    # Remplacement de la valeur dans le fichier de conf
    # Cas où on a souhaité exclure des versions majeures uniquement
    if [ "$READ_PACKAGES_TO_EXCLUDE_MAJOR" == "1" ];then
        sed -i "s/^EXCLUDE_MAJOR=.*/EXCLUDE_MAJOR=\"$READ_PACKAGES_TO_EXCLUDE\"/g" "$CONF"
    else
        sed -i "s/^EXCLUDE=.*/EXCLUDE=\"$READ_PACKAGES_TO_EXCLUDE\"/g" "$CONF"
    fi

    # Afficher un message de confirmation
}