#!/usr/bin/env bash
# Voir la liste des modules

function listModules
{
    # Récupération de tous les modules à jour depuis github
    getModules

    ENABLED_MODULES=()

    # Affiche les modules activés
    echo -e "\n Enabled modules:"
    if [ "$(ls -A $MODULES_ENABLED_DIR)" ];then
        for MODULE in $(ls -A1 "${MODULES_ENABLED_DIR}/"*.mod);do
            MODULE=$(basename $MODULE)
            MODULE=${MODULE%.mod}
            echo -e " $GREEN $MODULE $RESET"

            ENABLED_MODULES+=("$MODULE")
        done
    else
        echo " No module enabled"
    fi

    # Affiche les modules disponibles (qui ne sont pas dans ENABLED_MODULES)
    echo -e "\n Available modules:"
    if [ "$(ls -A $MODULES_DIR)" ];then
        for MODULE in $(ls -A1 "${MODULES_DIR}/"*.mod);do
            MODULE=$(basename $MODULE)
            MODULE=${MODULE%.mod}
            if [[ ! ${ENABLED_MODULES[*]} =~ "$MODULE" ]]; then
                MODULE=$(basename $MODULE | sed 's/.mod//g')
                echo -e " $YELLOW $MODULE $RESET"
            fi
        done
    fi
}