#!/usr/bin/env bash

# Vérifie la présence d'un lock yum et attend pour sa libération si c'est le cas

function checkYumLock
{
    if [ -f "/var/run/yum.pid" ];then
        echo -e "Waiting for yum ${YELLOW}lock${RESET}..."
    fi

    while [ -f "/var/run/yum.pid" ];do
        sleep 2
    done
}