#!/usr/bin/env bash
# Restart services after update

function restartService
{
    # If $SERVICE_TO_BE_RESTARTED contains services that need to be restarted
    if [ -z "$SERVICE_TO_BE_RESTARTED" ];then
        return
    fi

    OLD_IFS=$IFS
    IFS=' '

    for SERVICE in $(echo "$SERVICE_TO_BE_RESTARTED"); do
        # Clean eventual spaces
        SERVICE=$(echo "$SERVICE" | sed 's/ //g')

        echo -ne "→ Restarting ${YELLOW}${SERVICE}${RESET} service: "

        systemctl restart "$SERVICE" --quiet

        if [ "$?" != "0" ];then
            echo -e "[$YELLOW ERROR $RESET] while restarting"
        else
            echo -e "[$GREEN OK $RESET]"
        fi
    done

    IFS=$OLD_IFS
}