#!/usr/bin/env bash

function clean_exit
{
    # Clean temp files
    # rm "/opt/linupdate.maj.sh" -f
    # rm "/opt/reposconf/" -rf
    rm "$LOG_REPORT_MAIL" -f
    rm "/tmp/linupdate"* -rf
    rm "/tmp/.linupdate_${PROCID}"* -rf

    if [ "$MOD_ERROR" -gt "0" ];then
        sendMail
    fi

    rm "/tmp/linupdate.lock" -f

    if [ "$UPDATE_ERROR" -gt "0" ];then
        (( ERROR_STATUS++ ))
    fi

    exit $ERROR_STATUS
}