name: Build and test rpm package

on:
  push:
    branches: [ devel ]
  # pull_request:
  #   push:
  #     branches: [ main ]

jobs:
  build-rpm:
    name: Build rpm package
    runs-on: ubuntu-latest
    container:
      image: almalinux:9
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get linupdate version
        run: echo "VERSION=$(cat ${GITHUB_WORKSPACE}/version)" >> $GITHUB_ENV

      - name: Install dependencies packages
        run: dnf install rpmdevtools rpmlint -y

      - name: Create build environment
        run: |
          mkdir -p $HOME/rpmbuild/BUILD
          mkdir -p $HOME/rpmbuild/BUILDROOT
          mkdir -p $HOME/rpmbuild/RPMS
          mkdir -p $HOME/rpmbuild/SOURCES
          mkdir -p $HOME/rpmbuild/SPECS
          mkdir -p /etc/linupdate/modules
          mkdir -p /opt/linupdate
          mkdir -p /opt/linupdate/src/
          mkdir -p /opt/linupdate/templates/
          mkdir -p /lib/systemd/system/

      - name: Copy files to include in the build
        run: |
          cp -r ${GITHUB_WORKSPACE}/src/* /opt/linupdate/src/
          cp -r ${GITHUB_WORKSPACE}/templates/* /opt/linupdate/templates/
          cp ${GITHUB_WORKSPACE}/linupdate.py /opt/linupdate/linupdate.py
          cp ${GITHUB_WORKSPACE}/service.py /opt/linupdate/service.py
          cp ${GITHUB_WORKSPACE}/version /opt/linupdate/version
          cp ${GITHUB_WORKSPACE}/templates/linupdate.systemd.template /lib/systemd/system/linupdate.service

      - name: Copy spec file
        run: |
          cp ${GITHUB_WORKSPACE}/.github/workflows/packaging/rpm/spec $HOME/rpmbuild/SPECS/linupdate.spec
          sed -i "s/__VERSION__/${{ env.VERSION }}/g" $HOME/rpmbuild/SPECS/linupdate.spec

      - name: Build package
        run: |
          cd $HOME/rpmbuild/SPECS
          rpmbuild --target noarch -bb linupdate.spec
          mv $HOME/rpmbuild/RPMS/noarch/linupdate-${{ env.VERSION }}-stable.noarch.rpm /tmp/linupdate-test-build-${{ env.VERSION }}.noarch.rpm

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: linupdate-test-build-${{ env.VERSION }}.noarch.rpm
          path: /tmp/linupdate-test-build-${{ env.VERSION }}.noarch.rpm
          retention-days: 1

      # Upload package to test repositories
      - name: Upload packages to test repositories
        run: |
          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -F "files=@/tmp/linupdate-test-build-${{ env.VERSION }}.noarch.rpm" -F "overwrite=true" ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/980/upload
          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -F "files=@/tmp/linupdate-test-build-${{ env.VERSION }}.noarch.rpm" -F "overwrite=true" ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/981/upload

      # Rebuild repositories metadata
      - name: Rebuild repositories
        run: |
          curl --fail-with-body -X PUT -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -d '{"gpgSign":"true"}' ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/980/rebuild
          curl --fail-with-body -X PUT -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -d '{"gpgSign":"true"}' ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/981/rebuild

  # (EOL)
  # test-centos8:
  #   name: Install and test CentOS 8
  #   needs: build-rpm
  #   uses: ./.github/workflows/install-and-test-on-centos8.yml
  #   secrets: inherit

  # Fedora 40
  test-fedora40:
    name: Install and test on Fedora 40
    needs: build-rpm
    uses: ./.github/workflows/install-and-test-on-fedora40.yml
    secrets: inherit

  # Fedora 41
  # test-fedora41:
  #   name: Install and test on Fedora 41
  #   needs: build-rpm
  #   uses: ./.github/workflows/install-and-test-on-fedora41.yml
  #   secrets: inherit

 # Rocky Linux
  test-rockylinux9:
    name: Install and test on Rocky Linux 9
    needs: build-rpm
    uses: ./.github/workflows/install-and-test-on-rockylinux9.yml
    secrets: inherit

  # No docker image available yet
  # test-rockylinux10:

  # Alma Linux
  test-almalinux9:
    name: Install and test on Alma Linux 9
    needs: build-rpm
    uses: ./.github/workflows/install-and-test-on-almalinux9.yml
    secrets: inherit

  test-almalinux10:
    name: Install and test on Alma Linux 10
    needs: build-rpm
    uses: ./.github/workflows/install-and-test-on-almalinux10.yml
    secrets: inherit
