name: Build and test deb package

on:
  push:
    branches: [ devel ]
  # pull_request:
  #   push:
  #     branches: [ main ]

jobs:
  build-deb:
    name: Build deb package
    runs-on: ubuntu-latest
    container:
      image: debian:latest
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get linupdate version
        run: echo "VERSION=$(cat ${GITHUB_WORKSPACE}/version)" >> $GITHUB_ENV

      - name: Install dependencies packages
        run: apt-get update && apt-get install build-essential binutils lintian debhelper dh-make devscripts curl -y

      - name: Create build environment
        run: |
          mkdir -p /tmp/linupdate-build/DEBIAN
          mkdir -p /tmp/linupdate-build/etc/linupdate/modules
          mkdir -p /tmp/linupdate-build/opt/linupdate
          mkdir -p /tmp/linupdate-build/opt/linupdate/src/
          mkdir -p /tmp/linupdate-build/opt/linupdate/templates/

      - name: Copy files to include in the build
        run: |
          cp -r ${GITHUB_WORKSPACE}/src/* /tmp/linupdate-build/opt/linupdate/src/
          cp -r ${GITHUB_WORKSPACE}/templates/* /tmp/linupdate-build/opt/linupdate/templates/
          cp ${GITHUB_WORKSPACE}/linupdate.py /tmp/linupdate-build/opt/linupdate/linupdate.py
          cp ${GITHUB_WORKSPACE}/service.py /tmp/linupdate-build/opt/linupdate/service.py
          cp ${GITHUB_WORKSPACE}/version /tmp/linupdate-build/opt/linupdate/version

      - name: Copy control file
        run: |
          cp ${GITHUB_WORKSPACE}/.github/workflows/packaging/deb/control /tmp/linupdate-build/DEBIAN/control
          sed -i "s/__VERSION__/${{ env.VERSION }}/g" /tmp/linupdate-build/DEBIAN/control

      - name: Copy preinst and postinst script
        run: |
          cp ${GITHUB_WORKSPACE}/.github/workflows/packaging/deb/preinst /tmp/linupdate-build/DEBIAN/preinst
          cp ${GITHUB_WORKSPACE}/.github/workflows/packaging/deb/postinst /tmp/linupdate-build/DEBIAN/postinst
          chmod 755 /tmp/linupdate-build/DEBIAN/preinst /tmp/linupdate-build/DEBIAN/postinst

      - name: Build package
        run: |
          cd /tmp
          dpkg-deb --build linupdate-build
          mv /tmp/linupdate-build.deb /tmp/linupdate-test-build_${{ env.VERSION }}_all.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: linupdate-test-build_${{ env.VERSION }}_all.deb
          path: /tmp/linupdate-test-build_${{ env.VERSION }}_all.deb
          retention-days: 1

      # Upload package to test repositories
      - name: Upload packages to test repositories
        run: |
          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -F "files=@/tmp/linupdate-test-build_${{ env.VERSION }}_all.deb" -F "overwrite=true" ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/974/upload
          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -F "files=@/tmp/linupdate-test-build_${{ env.VERSION }}_all.deb" -F "overwrite=true" ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/975/upload
          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -F "files=@/tmp/linupdate-test-build_${{ env.VERSION }}_all.deb" -F "overwrite=true" ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/976/upload
          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -F "files=@/tmp/linupdate-test-build_${{ env.VERSION }}_all.deb" -F "overwrite=true" ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/977/upload
          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -F "files=@/tmp/linupdate-test-build_${{ env.VERSION }}_all.deb" -F "overwrite=true" ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/978/upload
          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -F "files=@/tmp/linupdate-test-build_${{ env.VERSION }}_all.deb" -F "overwrite=true" ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/979/upload

      # Rebuild repositories metadata
      - name: Rebuild repositories
        run: |
          curl --fail-with-body -X PUT -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -d '{"gpgSign":"true"}' ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/974/rebuild
          curl --fail-with-body -X PUT -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -d '{"gpgSign":"true"}' ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/975/rebuild
          curl --fail-with-body -X PUT -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -d '{"gpgSign":"true"}' ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/976/rebuild
          curl --fail-with-body -X PUT -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -d '{"gpgSign":"true"}' ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/977/rebuild
          curl --fail-with-body -X PUT -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -d '{"gpgSign":"true"}' ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/978/rebuild
          curl --fail-with-body -X PUT -H "Authorization: Bearer ${{ secrets.REPOSITORY_UPLOAD_TOKEN }}" -d '{"gpgSign":"true"}' ${{ secrets.REPOSITORY_UPLOAD_URL }}/api/v2/snapshot/979/rebuild

  #
  # Linupdate 3 is not working on Debian 10
  # install-debian-10:
  #

  # Try to install package on Debian 11
  install-debian-11:
    name: Install and test on Debian 11
    needs: build-deb
    uses: ./.github/workflows/install-and-test-on-debian11.yml
    secrets: inherit

  # Try to install package on Debian 12
  install-debian-12:
    name: Install and test on Debian 12
    needs: build-deb
    uses: ./.github/workflows/install-and-test-on-debian12.yml
    secrets: inherit

  # Try to install package on Debian 13
  install-debian-13:
    name: Install and test on Debian 13
    needs: build-deb
    uses: ./.github/workflows/install-and-test-on-debian13.yml
    secrets: inherit

  # Try to install package on Ubuntu 22.04
  install-ubuntu-2204:
    name: Install and test on Ubuntu 22.04
    needs: build-deb
    uses: ./.github/workflows/install-and-test-on-ubuntu-2204.yml
    secrets: inherit

  # Try to install package on Ubuntu 24.04
  install-ubuntu-2404:
    name: Install and test on Ubuntu 24.04
    needs: build-deb
    uses: ./.github/workflows/install-and-test-on-ubuntu-2404.yml
    secrets: inherit

  # Try to install package on Ubuntu 26.04
  install-ubuntu-2604:
    name: Install and test on Ubuntu 26.04
    needs: build-deb
    uses: ./.github/workflows/install-and-test-on-ubuntu-2604.yml
    secrets: inherit
